import { Prisma } from "@prisma/client";

import { prisma } from "../../database/prisma";
import { GitHubService } from "../github/github.service";
import { WorkflowDetectionService } from "./workflow-detection.service";
import {
  buildWorkflow,
  type PipelineGenerationInput,
} from "../../generators/workflow-builder";
import { YAMLGenerator } from "../../generators/yaml-generator";
import { parseGitHubRepo } from "../../utils/repo-parser";

type RepositoryPipelineInput = PipelineGenerationInput & {
  repositoryId: string;
};

type PipelineDbClient = Prisma.TransactionClient | typeof prisma;

/**
 * CI/CD Governance Safety Layer
 * 
 * Behavior:
 * 1. If repository has existing workflows: Generate governance analysis only (recommendation mode)
 * 2. If repository has NO workflows: Generate optional starter recommendations (recommendation mode)
 * 
 * IMPORTANT: Workflows are NEVER automatically committed or pushed to repositories.
 * This ensures Dependix operates as a CI/CD Governance Overlay, not a workflow replacement system.
 */
export class PipelineGeneratorService {
  /**
   * Check if repository has existing CI/CD workflows
   */
  private static async hasExistingWorkflows(
    repositoryId: string
  ): Promise<boolean> {
    try {
      const repository = await prisma.repository.findUnique({
        where: { id: repositoryId },
      });

      if (!repository) {
        return false;
      }

      const { owner, repo } = parseGitHubRepo(repository.url);
      const detection = await WorkflowDetectionService.detectExistingWorkflows(
        owner,
        repo
      );

      return detection.hasExistingWorkflow;
    } catch (error) {
      console.error("Error checking for existing workflows:", error);
      return false;
    }
  }

  /**
   * Add safety metadata to generated workflow
   * Indicates whether this is a recommendation or active workflow
   */
  private static addSafetyMetadata(
    yamlContent: string,
    isRecommendation: boolean
  ): string {
    const metadata = isRecommendation
      ? `# This is a governance recommendation generated by Dependix
# Do NOT commit this to your repository automatically
# This workflow is a suggestion for your CI/CD pipeline
# Review and manually implement if desired\n`
      : `# Generated by Dependix CI/CD Governance System\n`;

    return metadata + yamlContent;
  }

  static async createForRepository(
    input: RepositoryPipelineInput,
    db: PipelineDbClient = prisma
  ) {
    // Check if repository already has workflows (governance overlay mode)
    const hasExistingWorkflows = await this.hasExistingWorkflows(input.repositoryId);

    const workflow = buildWorkflow(input);
    let yamlContent = YAMLGenerator.generate(workflow);

    // Add safety metadata indicating this is a recommendation
    yamlContent = this.addSafetyMetadata(yamlContent, true);

    const client = db as any;
    
    return client.pipeline.create({
      data: {
        repositoryId: input.repositoryId,
        name: hasExistingWorkflows
          ? `[GOVERNANCE OVERLAY] ${workflow.name}`
          : `[RECOMMENDATION] ${workflow.name}`,
        yamlContent,
      },
    });
  }

  static async generateFromRepositoryId(repositoryId: string) {
    const repository = await prisma.repository.findUnique({
      where: {
        id: repositoryId,
      },
      include: {
        analysis: true,
      },
    });

    if (!repository?.analysis) {
      throw new Error("Repository or analysis not found for pipeline generation");
    }

    const pipeline = await this.createForRepository({
      repositoryId: repository.id,
      language: repository.analysis.language,
      framework: repository.analysis.framework,
      packageManager: repository.analysis.packageManager,
      hasDocker: repository.analysis.hasDocker,
      defaultBranch: repository.defaultBranch,
    });

    return pipeline;
  }

  static async getLatestByRepositoryId(repositoryId: string) {
    return (prisma as any).pipeline.findFirst({
      where: {
        repositoryId,
      },
      orderBy: {
        createdAt: "desc",
      },
    });
  }
}
